package com.chesscoach.app;
import org.junit.*;
import static org.junit.Assert.*;
import org.json.*;
import com.nimbusds.jose.*;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jose.jwk.*;
import com.nimbusds.jwt.*;
import java.io.*;
import java.net.*;
import java.security.*;
import java.security.interfaces.RSAPublicKey;
import java.security.interfaces.RSAPrivateKey;
import java.util.*;

public class ChatGptProtocolTest {
    private interface Work {void run()throws Exception;}
    private void rejects(Work work)throws Exception {try{work.run();fail("invalid input was accepted");}catch(IOException expected){}}
    private Map<String,String> query(String url)throws Exception {Map<String,String> out=new HashMap<>();for(String p:new URI(url).getRawQuery().split("&")){String[] pair=p.split("=",2);out.put(URLDecoder.decode(pair[0],"UTF-8"),URLDecoder.decode(pair[1],"UTF-8"));}return out;}
    @Test public void dynamicRegistrationUsesPkceAndPersistentHost()throws Exception {
        var a=ChatGptProtocol.attempt(12345,"dynamic_agent_client","");Map<String,String> q=query(ChatGptProtocol.authorize(a,"urn:uuid:host","",false));
        assertEquals("dynamic_agent_client",q.get("client_id"));assertEquals("urn:uuid:host",q.get("ext_agent_host_id"));assertEquals("ChessWithYourChatgpt",q.get("agent_name_hint"));assertEquals("http://127.0.0.1:12345/auth/callback",q.get("redirect_uri"));
        assertEquals("S256",q.get("code_challenge_method"));assertEquals(Base64.getUrlEncoder().withoutPadding().encodeToString(MessageDigest.getInstance("SHA-256").digest(a.verifier().getBytes("US-ASCII"))),q.get("code_challenge"));assertTrue(q.get("scope").contains("chatgpt.tokens.use.direct"));assertFalse(q.containsKey("client_secret"));assertNotEquals(a.state(),ChatGptProtocol.attempt(12345,"dynamic_agent_client","").state());
    }
    @Test public void returningRegistrationDoesNotReRegisterOrForceConsent()throws Exception {var a=ChatGptProtocol.attempt(32100,"oaiapp_saved","user");Map<String,String> q=query(ChatGptProtocol.authorize(a,"urn:uuid:host","",false));assertEquals("oaiapp_saved",q.get("client_id"));assertFalse(q.containsKey("agent_name_hint"));assertFalse(q.containsKey("prompt"));assertEquals("consent",query(ChatGptProtocol.authorize(a,"urn:uuid:host","",true)).get("prompt"));}
    @Test public void callbackRequiresIssuedClientAndOriginalState()throws Exception {var a=ChatGptProtocol.attempt(12345,"dynamic_agent_client","");String valid="/auth/callback?state="+a.state()+"&code=test&client_id=oaiapp_new";assertEquals("oaiapp_new",ChatGptProtocol.callback(a,valid).client());rejects(()->ChatGptProtocol.callback(a,valid.replace(a.state(),"wrong")));rejects(()->ChatGptProtocol.callback(a,valid.replace("&client_id=oaiapp_new","")));rejects(()->ChatGptProtocol.callback(a,valid+"&state="+a.state()));rejects(()->ChatGptProtocol.callback(a,valid.replace("/auth/callback","/callback")));}
    @Test public void callbackDenialExpiryAndAccountMixingAreRejected()throws Exception {var a=ChatGptProtocol.attempt(12345,"oaiapp_saved","user");assertEquals("oaiapp_saved",ChatGptProtocol.callback(a,"/auth/callback?state="+a.state()+"&code=test").client());rejects(()->ChatGptProtocol.callback(a,"/auth/callback?state="+a.state()+"&code=test&client_id=oaiapp_other"));rejects(()->ChatGptProtocol.callback(a,"/auth/callback?state="+a.state()+"&error=access_denied"));var expired=new ChatGptProtocol.Attempt(a.state(),a.nonce(),a.verifier(),a.redirect(),a.client(),a.subject(),1);rejects(()->ChatGptProtocol.callback(expired,"/auth/callback?state="+a.state()+"&code=test"));}
    private static RSAKey rsa;
    @BeforeClass public static void key()throws Exception {KeyPairGenerator g=KeyPairGenerator.getInstance("RSA");g.initialize(2048);KeyPair p=g.generateKeyPair();rsa=new RSAKey.Builder((RSAPublicKey)p.getPublic()).privateKey((RSAPrivateKey)p.getPrivate()).keyID("test-key").build();}
    private JWTClaimsSet.Builder claims(){return new JWTClaimsSet.Builder().issuer(ChatGptProtocol.ISSUER).subject("subject-a").audience("oaiapp_test").issueTime(new Date()).expirationTime(new Date(System.currentTimeMillis()+60000)).claim("nonce","nonce-a").claim("email","test@example.org");}
    private String jwt(JWTClaimsSet claims)throws Exception {SignedJWT jwt=new SignedJWT(new JWSHeader.Builder(JWSAlgorithm.RS256).keyID("test-key").build(),claims);jwt.sign(new RSASSASigner(rsa));return jwt.serialize();}
    private JSONObject identity(JWTClaimsSet claims,String expected)throws Exception{return ChatGptProtocol.identity(jwt(claims),new JWKSet(rsa.toPublicJWK()).toString(),"oaiapp_test","nonce-a",expected);}
    @Test public void validSignedIdentityIsAccepted()throws Exception {assertEquals("subject-a",identity(claims().build(),"subject-a").getString("subject"));}
    @Test public void wrongIssuerAudienceNonceAndSubjectAreRejected()throws Exception {rejects(()->identity(claims().issuer("https://evil.example").build(),""));rejects(()->identity(claims().audience("other-client").build(),""));rejects(()->identity(claims().claim("nonce","other-nonce").build(),""));rejects(()->identity(claims().build(),"other-user"));}
    @Test public void expiredAndFutureIdentityAreRejected()throws Exception {rejects(()->identity(claims().expirationTime(new Date(1)).build(),""));rejects(()->identity(claims().issueTime(new Date(System.currentTimeMillis()+60000)).build(),""));rejects(()->identity(claims().notBeforeTime(new Date(System.currentTimeMillis()+60000)).build(),""));}
    @Test public void signatureAndUnsignedTokensAreRejected()throws Exception {KeyPairGenerator g=KeyPairGenerator.getInstance("RSA");g.initialize(2048);KeyPair other=g.generateKeyPair();RSAKey wrong=new RSAKey.Builder((RSAPublicKey)other.getPublic()).keyID("test-key").build();rejects(()->ChatGptProtocol.identity(jwt(claims().build()),new JWKSet(wrong).toString(),"oaiapp_test","nonce-a",""));try{ChatGptProtocol.identity(new PlainJWT(claims().build()).serialize(),new JWKSet(rsa.toPublicJWK()).toString(),"oaiapp_test","nonce-a","");fail();}catch(java.text.ParseException expected){}}
    @Test public void identityOnlyDoesNotEnableInference()throws Exception {assertFalse(ChatGptProtocol.sharing(new JSONObject().put("access_token","test").put("scope","openid profile email")));assertFalse(ChatGptProtocol.sharing(new JSONObject().put("scope",ChatGptProtocol.SCOPE)));assertTrue(ChatGptProtocol.sharing(new JSONObject().put("access_token","test").put("scope",ChatGptProtocol.SCOPE)));}
    private String event(String type,String rest){return "data: {\"type\":\""+type+"\","+rest+"}\n\n";}
    @Test public void streamRequiresCompletedAndCollectsUsage()throws Exception {String s=event("response.output_text.delta","\"delta\":\"hello\"")+event("response.completed","\"response\":{\"status\":\"completed\",\"usage\":{\"input_tokens\":7}}")+"data: [DONE]\n\n";JSONObject r=ChatGptProtocol.completed(new StringReader(s));assertEquals("hello",r.getString("text"));assertEquals(7,r.getJSONObject("usage").getInt("input_tokens"));}
    @Test public void droppedOrIncompleteStreamIsNotSaved()throws Exception {rejects(()->ChatGptProtocol.completed(new StringReader(event("response.output_text.delta","\"delta\":\"partial\""))));rejects(()->ChatGptProtocol.completed(new StringReader(event("response.incomplete","\"response\":{}"))));rejects(()->ChatGptProtocol.completed(new StringReader("data: [DONE]\n\n")));}
    @Test public void midStreamUsageLimitOverridesPartialText()throws Exception {String s=event("response.output_text.delta","\"delta\":\"partial\"")+event("response.failed","\"response\":{\"error\":{\"code\":\"subscription_sharing_usage_limit_exceeded\"}}");try{ChatGptProtocol.completed(new StringReader(s));fail();}catch(ChatGptProtocol.ApiError e){assertTrue(e.limit());assertEquals("subscription_sharing_usage_limit_exceeded",e.code);}}
    @Test public void previewRequestUsesOnlySupportedStatelessFields()throws Exception {JSONObject r=ChatGptProtocol.responseRequest("account-model","context","instruction");assertFalse(r.getBoolean("store"));assertTrue(r.getBoolean("stream"));assertTrue(r.get("input") instanceof JSONArray);for(String field:new String[]{"max_output_tokens","temperature","previous_response_id","background","conversation","user"})assertFalse(r.has(field));}
    @Test public void directAdmissionAndRefreshErrorsRemainDistinct()throws Exception {var e=ChatGptProtocol.ApiError.from(403,new JSONObject().put("detail","not accepted"),"request-id");assertEquals(403,e.status);assertEquals("detail",e.shape);assertEquals("request-id",e.requestId);assertFalse(e.terminalRefresh());assertTrue(ChatGptProtocol.ApiError.from(400,new JSONObject().put("error","invalid_grant"),"").terminalRefresh());}
    @Test public void transientUsageLookupFailureIsNotExhaustion()throws Exception {var e=ChatGptProtocol.ApiError.from(503,new JSONObject().put("error",new JSONObject().put("code","subscription_sharing_usage_unavailable")),"");assertFalse(e.limit());assertFalse(e.terminalRefresh());}
    @Test public void rotatingTokenUpdateRetainsGrantAndReplacesBothTokens()throws Exception {JSONObject profile=new JSONObject().put("refresh_token","old-refresh").put("scope",ChatGptProtocol.SCOPE).put("id_token","original-verified-id");JSONObject update=new JSONObject().put("access_token","new-access").put("refresh_token","new-refresh").put("token_type","Bearer").put("expires_in",3600);ChatGptAccounts.replaceTokens(profile,update,true);assertEquals("new-access",profile.getString("access_token"));assertEquals("new-refresh",profile.getString("refresh_token"));assertTrue(ChatGptProtocol.sharing(profile));assertEquals("original-verified-id",profile.getString("id_token"));}
}
