package com.chesscoach.app;
import java.util.*;
import org.json.*;
import org.junit.Test;
import static org.junit.Assert.*;
public class CoachDiagramsTest {
    private JSONObject details()throws Exception{var actual=new Stockfish.Line(1,20,30,null,List.of("e2e4","e7e5","g1f3","b8c6"));return AnalysisJson.details(new Stockfish.Analysis("e2e4",List.of(actual)),actual,null);}
    @Test public void markersNeverLeakAtAnyStreamingBoundary(){String raw="중앙을 준비합니다.{viz:a2}\n다음에는 전개합니다.";for(int i=0;i<=raw.length();i++){String visible=CoachDiagrams.visible(raw.substring(0,i));assertFalse(visible.contains("{"));assertFalse(visible.contains("viz:"));assertFalse(visible.contains("a2}"));}assertEquals("중앙을 준비합니다.\n다음에는 전개합니다.",CoachDiagrams.visible(raw));}
    @Test public void unknownMalformedAndNestedMetadataIsHidden(){assertEquals("앞뒤",CoachDiagrams.visible("앞{viz:unknown}뒤"));assertEquals("앞뒤",CoachDiagrams.visible("앞{outer {viz:a0}}뒤"));assertEquals("앞",CoachDiagrams.visible("앞{viz:a"));assertEquals("평문",CoachDiagrams.visible("평문"));assertEquals("앞뒤",CoachDiagrams.visible("앞}뒤"));}
    @Test public void boardBelongsToItsExplanationAndAppearsOnlyAfterCompleteMarker(){var parts=CoachDiagrams.parts("첫 설명{viz:a0}\n둘째 설명{viz:a2}\n다음 글");assertEquals("첫 설명",parts.get(0).text());assertEquals("a0",parts.get(0).diagramId());assertEquals("\n둘째 설명",parts.get(1).text());assertEquals("a2",parts.get(1).diagramId());assertEquals("다음 글",parts.get(2).text().trim());assertEquals("",CoachDiagrams.parts("첫 설명{viz:a0").get(0).diagramId());}
    @Test public void selectedDiagramsUseActualFuturePositionNotInitialBoard()throws Exception{var catalog=CoachDiagrams.catalog(new Chess(),details());var selected=CoachDiagrams.selected(catalog,"나이트를 전개하세요.{viz:a2}");assertEquals(1,selected.size());Chess position=new Chess();position.play(Chess.Move.parse("e2e4"));position.play(Chess.Move.parse("e7e5"));assertEquals(position.fen(),selected.get(0).fen());assertEquals("g1f3",selected.get(0).move());assertTrue(new Chess(selected.get(0).fen()).legalMoves().contains(Chess.Move.parse(selected.get(0).move())));}
    @Test public void unknownReferencesCannotInjectBoardsAndDuplicatesAreBounded()throws Exception{var catalog=CoachDiagrams.catalog(new Chess(),details());assertTrue(CoachDiagrams.selected(catalog,"{viz:a99}{viz:n99}").isEmpty());assertEquals(1,CoachDiagrams.selected(catalog,"{viz:a2}{viz:a2}{viz:c2}").size());assertTrue(CoachDiagrams.selected(catalog,"기물을 전개하세요.").isEmpty());}
    @Test public void illegalPvStopsWithoutProducingInvalidFutureBoards()throws Exception{Stockfish.Line line=new Stockfish.Line(1,20,0,null,List.of("e2e4","e7e4","g1f3"));JSONObject bad=AnalysisJson.details(new Stockfish.Analysis("e2e4",List.of(line)),line,null);var catalog=CoachDiagrams.catalog(new Chess(),bad);assertTrue(catalog.containsKey("a0"));assertFalse(catalog.containsKey("a1"));assertFalse(catalog.containsKey("a2"));}
    @Test public void payloadCatalogContainsStableChoicesWithoutModelControlledFen()throws Exception{var catalog=CoachDiagrams.catalog(new Chess(),details());JSONArray evidence=CoachDiagrams.evidence(catalog);assertEquals("a0",evidence.getJSONObject(0).getString("id"));assertEquals("e4",evidence.getJSONObject(0).getString("moveSAN"));assertFalse(evidence.toString().contains("fen"));assertEquals(catalog.keySet(),CoachDiagrams.catalog(new Chess(),details()).keySet());}
    @Test public void visualsRequireNewProtocolButOldStrategyCacheStillReads()throws Exception{JSONObject response=new JSONObject().put("explanation",new JSONObject().put("strategy","원칙").put("continuation","진행").put("principle","학습"));JSONObject cache=new JSONObject().put("response",response);assertTrue(CoachText.lesson(cache));assertFalse(CoachText.visualLesson(cache));response.put("visualVersion",1);assertTrue(CoachText.visualLesson(cache));}
}
