package com.chesscoach.app;
import org.json.*;
import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;
public class CoachContextTest {
    private Pgn.Game game(){return Pgn.parse("1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. d3 d6 *");}
    private JSONObject source(Pgn.Game game,int at)throws Exception{return new JSONObject().put("before",game.plies().get(at-1).before()).put("after",game.plies().get(at-1).after()).put("played",game.plies().get(at-1).uci());}
    @Test public void historyStopsAtSelectedPositionAndDoesNotMutateInput()throws Exception{var game=game();JSONObject source=source(game,3);String original=source.toString();JSONObject out=CoachContext.attach(source,game,3,false,new JSONObject());assertEquals("1. e4 e5 2. Nf3",out.getJSONObject("gameContext").getString("historySAN"));assertEquals("black",out.getJSONObject("gameContext").getString("playerSide"));assertFalse(out.toString().contains("Nc6"));assertEquals(original,source.toString());}
    @Test public void openingHasPositionSpecificObservationsAndRecognizedName()throws Exception{var game=game();JSONObject ctx=CoachContext.attach(source(game,5),game,5,true,new JSONObject()).getJSONObject("gameContext");assertEquals("opening",ctx.getString("phase"));assertEquals("이탈리안 게임",ctx.getString("openingName"));String home=ctx.getJSONObject("observations").getJSONArray("minorPiecesOnHomeSquares").toString();assertFalse(home.contains("g1"));assertFalse(home.contains("f1"));assertTrue(home.contains("b1"));}
    @Test(expected=IllegalArgumentException.class) public void mismatchedHistoryCannotBeSent()throws Exception{var game=game();CoachContext.attach(source(game,4),game,3,true,new JSONObject());}
    @Test public void customFenIsNotInventedOpeningAndKeepsFullmoveNumbers()throws Exception{String initial="4k3/8/8/8/8/8/4P3/4K3 b - - 0 17";var game=Pgn.parse("[FEN \""+initial+"\"] 17... Kf7 18. e4 *");JSONObject ctx=CoachContext.attach(source(game,1),game,1,false,new JSONObject()).getJSONObject("gameContext");assertEquals("17... Kf7",ctx.getString("historySAN"));assertEquals("",ctx.getString("openingName"));assertEquals("endgame",ctx.getString("phase"));}
    @Test public void oldSavedEngineVariationsUpgradeToMultiMoveEvidence()throws Exception{var game=game();Stockfish.Line line=new Stockfish.Line(1,22,34,null,List.of("e2e4","e7e5","g1f3","b8c6","f1c4","g8f6","d2d3","d7d6"));JSONObject details=AnalysisJson.details(new Stockfish.Analysis("e2e4",List.of(line)),line,null);JSONObject stored=new JSONObject().put("0",new JSONObject().put("details",details).put("local","좋은 수"));JSONObject out=CoachContext.attach(source(game,1),game,1,true,stored);assertEquals(8,out.getJSONObject("playedScore").getJSONArray("continuationSAN").length());assertEquals("Nf3",out.getJSONObject("playedScore").getJSONArray("continuationSAN").getString(2));assertEquals(8,out.getJSONArray("candidates").getJSONObject(0).getJSONArray("pv").length());assertFalse(stored.toString().contains("continuationSAN"));}
}
