package com.chesscoach.app;
import android.app.*;
import android.content.*;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.widget.*;
import org.json.*;
import java.util.concurrent.*;
/** Browser device login delegates credentials to the official Codex CLI on the service. */
public final class ConnectionActivity extends Activity {
    private final ExecutorService jobs=Executors.newSingleThreadExecutor();private final Handler handler=new Handler(Looper.getMainLooper());
    private CoachClient client;private TextView status,code;private EditText endpoint,pairing;private Button login,model;private boolean destroyed=false,polling=false,resumed=false;
    @Override public void onCreate(Bundle state){super.onCreate(state);client=new CoachClient(this);LinearLayout root=Ui.screen(this,true);Ui.header(this,root,"AI 코치");root.addView(Ui.text(this,"한 수의 이유를,\n더 쉽게 이해하세요.",28,true));Ui.gap(root,12);root.addView(Ui.text(this,"ChatGPT 계정으로 코치를 연결하고 대국 중에도 원하는 모델을 선택하세요.",15,false));Ui.gap(root,24);
        LinearLayout card=Ui.card(this);card.addView(Ui.text(this,"코치 서비스 연결",18,true));Ui.gap(card,8);TextView note=Ui.text(this,"현재는 본인 PC/서버의 설명 서비스가 필요합니다. 공식 Codex 기기 인증이 서비스에서 실행되며, OAuth 자격 증명은 휴대폰에 저장하지 않습니다.",13,false);note.setTextColor(getColor(R.color.muted));card.addView(note);Ui.gap(card,14);
        endpoint=field(card,"서비스 HTTPS 주소",getSharedPreferences("coach",0).getString("endpoint",""));endpoint.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);pairing=field(card,"서비스 연결 코드 · 기존 코드 유지 가능","");pairing.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);Ui.gap(card,8);card.addView(Ui.button(this,"서비스 연결 확인",()->connect(false)));root.addView(card);Ui.gap(root,20);
        login=Ui.primary(this,"ChatGPT로 로그인 · 브라우저 열기",()->connect(true));root.addView(login);Ui.gap(root,12);code=Ui.text(this,"",18,true);root.addView(code);status=Ui.text(this,"로그인 화면은 기본 브라우저에서 열립니다. 계정에서 기기 코드 인증을 허용해야 할 수 있습니다.",14,false);status.setTextColor(getColor(R.color.muted));root.addView(status);Ui.gap(root,20);model=Ui.button(this,Ui.modelLabel(this)+" · 모델 선택",()->Ui.models(this,()->model.setText(Ui.modelLabel(this)+" · 모델 선택")));root.addView(model);Ui.gap(root,12);root.addView(Ui.button(this,"연결 해제",()->{getSharedPreferences("coach",0).edit().remove("endpoint").remove("token").remove("iv").apply();polling=false;handler.removeCallbacksAndMessages(null);endpoint.setText("");code.setText("");status.setText("이 기기의 서비스 연결을 해제했습니다.");}));}
    private EditText field(LinearLayout root,String label,String value){root.addView(Ui.text(this,label,12,false));EditText e=new EditText(this);e.setSingleLine(true);e.setTextColor(getColor(R.color.ink));e.setText(value);e.setMinHeight(Ui.dp(this,48));root.addView(e);return e;}
    private void connect(boolean browser){try{String url=endpoint.getText().toString().trim();CoachClient.validateEndpoint(url);if(!pairing.getText().toString().trim().isEmpty())client.saveToken(pairing.getText().toString().trim());getSharedPreferences("coach",0).edit().putString("endpoint",url).apply();pairing.setText("");}catch(Exception e){status.setText("서비스 주소와 연결 코드를 먼저 확인해 주세요.");return;}login.setEnabled(false);status.setText(browser?"브라우저 로그인 준비 중…":"서비스와 계정 상태 확인 중…");jobs.submit(()->{try{loadModels();JSONObject auth=client.request("/v1/auth/status",null);if(auth.optBoolean("signedIn")){runOnUiThread(()->complete());return;}if(!browser){runOnUiThread(()->{login.setEnabled(true);status.setText("서비스 연결 완료. ChatGPT로 로그인을 눌러 계정을 연결하세요.");});return;}JSONObject result=client.request("/v1/auth/device",new JSONObject());runOnUiThread(()->open(result));}catch(Exception e){runOnUiThread(()->{if(!destroyed){login.setEnabled(true);status.setText("로그인을 준비하지 못했어요. 서비스 주소·연결 코드와 서버의 Codex 실행 환경을 확인해 주세요.");}});}});}
    private void loadModels()throws Exception{JSONObject response=client.request("/v1/models",null);JSONArray array=response.getJSONArray("models");java.util.List<String> names=new java.util.ArrayList<>();for(int i=0;i<array.length();i++)names.add(array.getString(i));if(names.isEmpty())throw new Exception("No models");var edit=getSharedPreferences("coach",0).edit().putString("models",String.join(",",names));if(!names.contains(Ui.model(this)))edit.putString("model",response.optString("defaultModel",names.get(0)));edit.apply();}
    private void open(JSONObject result){if(destroyed)return;login.setEnabled(true);if(result.optString("status").equals("signedIn")){complete();return;}if(result.optString("status").equals("starting")){polling=true;status.setText("공식 로그인 화면을 준비하고 있어요…");schedule();return;}String url=result.optString("verificationUrl"),value=result.optString("userCode");Uri uri=Uri.parse(url);if(!"https".equals(uri.getScheme())||!"auth.openai.com".equals(uri.getHost())||!"/codex/device".equals(uri.getPath())||!value.matches("[A-Z0-9-]{6,24}")){status.setText("서비스에서 유효한 공식 로그인 화면을 제공하지 못했어요.");return;}code.setText("로그인 코드  "+value+"  · 탭해서 복사");code.setOnClickListener(v->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("로그인 코드",value));Toast.makeText(this,"로그인 코드를 복사했습니다",Toast.LENGTH_SHORT).show();});status.setText("브라우저에서 로그인하고 위 코드를 입력하세요. 앱으로 돌아오면 연결을 확인합니다.");polling=true;try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(ActivityNotFoundException e){status.setText("브라우저를 열 수 없어요. auth.openai.com/codex/device에서 위 코드를 입력하세요.");}schedule();}
    private void complete(){if(destroyed)return;polling=false;handler.removeCallbacksAndMessages(null);login.setEnabled(true);code.setText("");model.setText(Ui.modelLabel(this)+" · 모델 선택");status.setText("✓ ChatGPT 계정 연결 완료. 대국 화면에서 조언을 받을 수 있어요.");}
    private void schedule(){if(!polling||destroyed||!resumed)return;handler.postDelayed(()->jobs.submit(()->{try{JSONObject state=client.request("/v1/auth/device",null);runOnUiThread(()->{if(destroyed)return;if(state.optString("status").equals("signedIn"))complete();else if(state.optString("status").equals("failed")||state.optString("status").equals("expired")){polling=false;code.setText("");status.setText("로그인이 완료되지 않았어요. 브라우저 로그인 버튼으로 다시 시도하세요.");}else if(state.optString("status").equals("waiting")&&code.getText().length()==0)open(state);else schedule();});}catch(Exception e){runOnUiThread(()->{if(!destroyed){polling=false;status.setText("로그인 상태를 확인하지 못했어요. 서비스 연결을 다시 확인하세요.");}});}}),3000);}
    @Override protected void onResume(){super.onResume();resumed=true;if(polling){handler.removeCallbacksAndMessages(null);schedule();}}
    @Override protected void onPause(){resumed=false;handler.removeCallbacksAndMessages(null);super.onPause();}
    @Override protected void onDestroy(){destroyed=true;handler.removeCallbacksAndMessages(null);jobs.shutdownNow();super.onDestroy();}
}
