package com.chesscoach.app;
import android.app.Activity;
import android.os.Bundle;
import android.content.*;
import android.widget.*;
import android.text.InputFilter;
public final class ImportActivity extends Activity {
    private EditText title,input;private TextView status;
    @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout root=Ui.screen(this,true);Ui.header(this,root,"기록 추가");root.addView(Ui.text(this,"기보를 붙여넣으세요.",27,true));Ui.gap(root,8);root.addView(Ui.text(this,"추천수와 학습 하이라이트를 찾아,\n직접 둔 대국과 같은 기록에 저장해요.",15,false));Ui.gap(root,24);root.addView(Ui.text(this,"기록 이름 · 선택",12,true));title=new EditText(this);title.setSingleLine();title.setTextColor(getColor(R.color.ink));title.setHint("예: 오늘의 연습 대국");Ui.input(title);root.addView(title);Ui.gap(root,16);root.addView(Ui.text(this,"PGN / SAN / 좌표 수순",12,true));input=new EditText(this);input.setTextColor(getColor(R.color.ink));input.setGravity(android.view.Gravity.TOP);input.setMinLines(7);input.setMaxLines(12);input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(100000)});input.setHint("1. e4 e5 2. Nf3 Nc6 *\n\n또는 e2e4 e7e5 g1f3 b8c6");Ui.input(input);root.addView(input);Ui.gap(root,12);LinearLayout tools=new LinearLayout(this);tools.addView(Ui.button(this,"붙여넣기",()->{android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(c.hasPrimaryClip()&&c.getPrimaryClip()!=null)input.setText(c.getPrimaryClip().getItemAt(0).coerceToText(this));}),new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));tools.addView(Ui.button(this,"파일 열기",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,10);}),new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));root.addView(tools);Ui.gap(root,12);status=Ui.text(this,"한 대국의 메인 수순을 가져옵니다. 주석과 가지 변화는 제외하며 최대 600반수까지 지원합니다.",12,false);status.setTextColor(getColor(R.color.muted));root.addView(status);Ui.gap(root,20);root.addView(Ui.primary(this,"추가하고 분석하기",this::save));}
    private void save(){try{Pgn.Game game=Pgn.parse(input.getText().toString());if(game.plies().isEmpty())throw new IllegalArgumentException("분석할 수순이 없습니다.");String name=title.getText().toString().trim();if(name.isEmpty())name=game.tags().getOrDefault("White","백")+" vs "+game.tags().getOrDefault("Black","흑");long id=Records.get(this).create(name,"imported",game);startActivity(new Intent(this,ReviewActivity.class).putExtra("recordId",id).putExtra("autoAnalyze",true));finish();}catch(Exception e){input.setError(e.getMessage());status.setText("기보를 확인해 주세요. "+e.getMessage());}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=10||result!=RESULT_OK||data==null||data.getData()==null)return;try(var stream=getContentResolver().openInputStream(data.getData())){if(stream==null)return;java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=stream.read(b))!=-1){if(out.size()+n>100000)throw new IllegalArgumentException("기보 파일은 100KB 이내로 선택해 주세요.");out.write(b,0,n);}input.setText(new String(out.toByteArray(),java.nio.charset.StandardCharsets.UTF_8));}catch(Exception e){status.setText("파일을 읽지 못했어요. "+e.getMessage());}}
}
