package com.chesscoach.app;
import android.app.*;
import android.os.*;
import android.content.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

/** Native play screen: pinned advice, live model picker, board-first visual feedback. */
public final class MainActivity extends Activity {
    private Chess game=new Chess();private volatile Stockfish engine,opponent;
    private final ExecutorService engineJobs=EngineWork.queue(),coachJobs=Executors.newSingleThreadExecutor();
    private final List<String> moves=new ArrayList<>(),fens=new ArrayList<>();
    private final Map<String,Integer> repetitions=new HashMap<>();private final List<Integer> trend=new ArrayList<>();private final List<Feedback> feedback=new ArrayList<>();
    private volatile int generation=0;private volatile boolean destroyed=false,parked=false;
    private boolean busy=true,preview=false;private int focus=-1;
    private BoardView board;private TextView status,evaluation,coach,moveLabel,planUse;private Button modelChip,suggestion,undoButton;
    private LinearLayout moveStrip;private SharedPreferences prefs;private CoachClient client;private long recordId;private int BG,INK,MUTED;
    private static class Feedback {String local,ai="",pendingModel="",aiModel="";boolean pending;int requestVersion;JSONObject payload,details;Feedback(String s){local=s;}}
    @Override public void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences("coach",0);client=new CoachClient(this);BG=getColor(R.color.background);INK=getColor(R.color.ink);MUTED=getColor(R.color.muted);buildUi();
        if(getIntent().getBooleanExtra("newGame",false)){repetitions.put(game.key(),1);save();getIntent().removeExtra("newGame");}else restore();connectEngine();}
    private int dp(int n){return Ui.dp(this,n);}private TextView text(String s,int size,int color){TextView t=Ui.text(this,s,size,false);t.setTextColor(color);return t;}
    private Button button(String s,Runnable action){return Ui.button(this,s,action);}
    private void buildUi(){
        LinearLayout root=Ui.screen(this,false);LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.addView(button("‹",this::finish),new LinearLayout.LayoutParams(dp(44),dp(44)));TextView title=Ui.text(this,"대국",20,true);title.setPadding(dp(10),0,0,0);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));header.addView(button("⋯",this::menu),new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(header);Ui.gap(root,8);
        LinearLayout advice=Ui.card(this);advice.setPadding(dp(14),dp(10),dp(14),dp(12));LinearLayout coachHeader=new LinearLayout(this);coachHeader.setGravity(Gravity.CENTER_VERTICAL);coachHeader.addView(Ui.text(this,"AI 코치",14,true),new LinearLayout.LayoutParams(0,-2,1));modelChip=button(Ui.modelLabel(this)+" ⌄",this::chooseModel);modelChip.setMinHeight(dp(36));coachHeader.addView(modelChip,new LinearLayout.LayoutParams(-2,dp(40)));advice.addView(coachHeader);planUse=Ui.text(this,"Using ChatGPT plan · Manage usage",11,false);planUse.setTextColor(MUTED);planUse.setOnClickListener(v->Ui.usage(this));advice.addView(planUse);Ui.gap(advice,4);coach=text("첫 수를 두면 판단의 근거와 다음 계획을 알려드려요.",15,INK);coach.setMaxLines(4);coach.setEllipsize(android.text.TextUtils.TruncateAt.END);coach.setMinHeight(dp(54));coach.setOnClickListener(v->{if(!ChatGptAccounts.connected(this))startActivity(new Intent(this,ConnectionActivity.class));else details();});advice.addView(coach);root.addView(advice);Ui.gap(root,8);
        LinearLayout info=new LinearLayout(this);info.setGravity(Gravity.CENTER_VERTICAL);status=text("Stockfish 준비 중…",12,MUTED);info.addView(status,new LinearLayout.LayoutParams(0,dp(28),1));moveLabel=text("",12,INK);moveLabel.setOnClickListener(v->Ui.legend(this));info.addView(moveLabel);root.addView(info);
        FrameLayout frame=new FrameLayout(this);board=new BoardView(this);board.onSquare=this::select;FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER);frame.addView(board,bp);root.addView(frame,new LinearLayout.LayoutParams(-1,0,1));
        evaluation=text("백 기준 평가 · 분석 대기",12,MUTED);evaluation.setGravity(Gravity.CENTER_VERTICAL);root.addView(evaluation,new LinearLayout.LayoutParams(-1,dp(30)));
        HorizontalScrollView strip=new HorizontalScrollView(this);strip.setHorizontalScrollBarEnabled(false);moveStrip=new LinearLayout(this);strip.addView(moveStrip);root.addView(strip,new LinearLayout.LayoutParams(-1,dp(38)));Ui.gap(root,6);
        LinearLayout controls=new LinearLayout(this);suggestion=button("추천수 보기",()->{preview=!preview;refresh();});undoButton=button("무르기",this::undo);Button retry=button("다시 설명",()->{if(focus>=0)requestExplanation(feedback.get(focus),generation);else startActivity(new Intent(this,ConnectionActivity.class));});for(Button b:new Button[]{suggestion,retry,undoButton}){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(48),1);lp.setMargins(dp(2),0,dp(2),0);controls.addView(b,lp);}root.addView(controls);
    }
    private void menu(){new AlertDialog.Builder(this).setTitle("대국 메뉴").setItems(new String[]{"대국 기록","새 대국 · 난이도 선택","AI 코치 연결","수 평가 표시 안내"},(d,n)->{if(n==0)startActivity(new Intent(this,RecordsActivity.class));else if(n==1){startActivity(new Intent(this,GameSetupActivity.class));finish();}else if(n==2)startActivity(new Intent(this,ConnectionActivity.class));else Ui.legend(this);}).show();}
    private void chooseModel(){Ui.models(this,()->{modelChip.setText(Ui.modelLabel(this)+" ⌄");if(focus>=0){for(Feedback other:feedback){other.requestVersion++;other.pending=false;}Feedback f=feedback.get(focus);requestExplanation(f,generation);}renderFeedback();});}
    private void details(){ScrollView scroll=new ScrollView(this);LinearLayout content=Ui.card(this);if(focus>=0){Feedback f=feedback.get(focus);content.addView(text(currentAdvice(f),16,INK));Ui.gap(content,20);content.addView(text(f.local,14,MUTED));}scroll.addView(content);new AlertDialog.Builder(this).setTitle("이번 수의 조언").setView(scroll).setPositiveButton("닫기",null).show();}
    private void connectEngine(){busy=true;int epoch=generation;engineJobs.submit(()->{if(destroyed||parked)return;try{if(engine==null)engine=new Stockfish(getApplicationInfo().nativeLibraryDir+"/libstockfish.so");if(opponent==null)opponent=new Stockfish(getApplicationInfo().nativeLibraryDir+"/libstockfish.so");if(destroyed){closeEngines();return;}runOnUiThread(()->{if(epoch!=generation||destroyed||parked)return;busy=false;refresh();if(!feedback.isEmpty()&&feedback.get(feedback.size()-1).details==null){int ply=feedback.size()-1;Chess before=new Chess(ply==0?Chess.START:fens.get(ply-1));busy=true;analyzePlayed(before,game.copy(),Chess.Move.parse(moves.get(ply)),feedback.get(ply),ply,epoch,!before.white);}else if(!game.white&&game.terminal(repetitions.getOrDefault(game.key(),1))==null)botTurn(epoch);});}catch(Exception e){runOnUiThread(()->{if(epoch==generation&&!destroyed){busy=true;status.setText("엔진 준비 실패");coach.setText("대국 메뉴에서 새 대국으로 다시 시작해 주세요.");}});}});}
    private void select(int s){if(preview){preview=false;refresh();return;}if(busy||!game.white||game.terminal(repetitions.getOrDefault(game.key(),1))!=null)return;List<Chess.Move> legal=game.legalMoves(),choices=new ArrayList<>();for(var m:legal)if(m.from()==board.selected&&m.to()==s)choices.add(m);if(!choices.isEmpty()){if(choices.size()>1)new AlertDialog.Builder(this).setTitle("승격 기물").setItems(new String[]{"퀸","룩","비숍","나이트"},(d,w)->play(choices.get(w),generation,false)).show();else play(choices.get(0),generation,false);return;}board.selected=game.squares[s]!='.'&&Chess.color(game.squares[s])?s:-1;board.targets.clear();for(var m:legal)if(m.from()==board.selected)board.targets.add(m.to());board.invalidate();}
    private void play(Chess.Move move,int epoch,boolean bot){
        if(epoch!=generation||destroyed||parked)return;Chess before=game.copy();busy=true;preview=false;board.selected=-1;board.targets.clear();game.play(move);moves.add(move.uci());fens.add(game.fen());repetitions.merge(game.key(),1,Integer::sum);board.setLastMove(move);
        Feedback entry=new Feedback((before.white?"내 수":"상대 수")+" · "+before.san(move)+"\n수의 평가를 계산하고 있어요.");feedback.add(entry);int ply=feedback.size()-1;if(!bot||focus<0)focus=ply;save();persistFeedback(entry,ply);refresh();analyzePlayed(before,game.copy(),move,entry,ply,epoch,bot);
    }
    private void analyzePlayed(Chess before,Chess after,Chess.Move move,Feedback entry,int ply,int epoch,boolean bot){engineJobs.submit(()->{try{var analysis=engine.analyze(before,bot?650:1300,3,null);Stockfish.Line played=null;for(var l:analysis.lines())if(!l.pv().isEmpty()&&l.pv().get(0).equals(move.uci()))played=l;if(played==null)played=engine.analyze(before,850,1,move.uci()).top();var afterAnalysis=engine.analyze(after,550,1,null);Stockfish.Line actual=played;runOnUiThread(()->{if(epoch!=generation||destroyed)return;var judgment=MoveJudgment.assess(before,move.uci(),analysis,actual);entry.local=judgment.kind().label+" · "+before.san(move)+"\n"+judgment.reason();if(afterAnalysis.top()!=null){trend.add(afterAnalysis.top().cp());if(trend.size()>6)trend.remove(0);evaluation.setText("백 기준 "+afterAnalysis.top().score()+" · 깊이 "+afterAnalysis.top().depth());}try{entry.payload=CoachClient.payload(before,after,move.uci(),analysis,actual,Ui.model(this),new ArrayList<>(trend));entry.details=AnalysisJson.details(analysis,actual,afterAnalysis).put("judgment",judgment.kind().name()).put("opponentDifficulty",Difficulty.from(prefs.getString("difficulty","ELO_1600")).label);}catch(Exception ignored){}save();persistFeedback(entry,ply);busy=false;refresh();requestExplanation(entry,epoch);if(!parked&&!game.white&&game.terminal(repetitions.getOrDefault(game.key(),1))==null)botTurn(epoch);});}catch(Exception e){runOnUiThread(()->{if(epoch==generation&&!destroyed){busy=true;status.setText("분석 중단 · 수는 저장됨");coach.setText("다시 대국을 열면 이어서 분석할 수 있어요.");closeEngines();}});}});}
    private void botTurn(int epoch){if(epoch!=generation||destroyed||parked)return;busy=true;status.setText("Stockfish가 생각하는 중…");Chess position=game.copy();engineJobs.submit(()->{try{opponent.setDifficulty(Difficulty.from(prefs.getString("difficulty","ELO_1600")));var analysis=opponent.analyze(position,900,1,null);Chess.Move m=Chess.Move.parse(analysis.best());runOnUiThread(()->{if(epoch==generation&&!parked)play(m,epoch,true);});}catch(Exception e){runOnUiThread(()->{if(epoch==generation&&!destroyed)status.setText("응수 준비 실패 · 대국을 다시 열어 주세요");});}});}
    private void requestExplanation(Feedback entry,int epoch){
        if(entry.payload==null)return;String model=Ui.model(this);if(entry.pending&&model.equals(entry.pendingModel))return;
        if(!ChatGptAccounts.connected(this)){entry.ai="AI 코치를 연결하면 방금 수의 이유와 다음 계획을 알려드려요. 연결하기 →";renderFeedback();return;}
        JSONObject cache=cached(entry,model);if(cache!=null){entry.ai=cache.optString("text");renderFeedback();return;}
        int version=++entry.requestVersion;entry.pending=true;entry.pendingModel=model;entry.ai="방금 수의 판단과 다음 계획을 생각하고 있어요…";renderFeedback();final long targetRecord=recordId;final int targetPly=feedback.indexOf(entry);JSONObject request;try{request=new JSONObject(entry.payload.toString()).put("model",model);}catch(Exception e){entry.pending=false;return;}
        coachJobs.submit(()->{if(destroyed||entry.requestVersion!=version)return;String result;try{JSONObject response=client.request("/v1/explain",request);result=AnalysisJson.explanation(response);Records.get(this).explanation(targetRecord,targetPly,response,result);}catch(Exception e){result=e.getMessage()==null?"조언 연결을 확인해 주세요.":e.getMessage();}String finalResult=result;runOnUiThread(()->{if(entry.requestVersion!=version)return;entry.pending=false;if(epoch==generation&&!destroyed){entry.ai=finalResult;entry.aiModel=model;save();renderFeedback();}});});
    }
    private JSONObject cached(Feedback f,String model){if(recordId==0)return null;var saved=Records.get(this).find(recordId);if(saved==null)return null;JSONObject e=saved.analyses().optJSONObject(Integer.toString(feedback.indexOf(f)));if(e==null)return null;JSONObject all=e.optJSONObject("aiByModel");if(all!=null&&all.optJSONObject(model)!=null)return all.optJSONObject(model);JSONObject response=e.optJSONObject("aiResponse");if(response!=null&&model.equals(response.optString("model")))try{return new JSONObject().put("response",response).put("text",e.optString("aiText"));}catch(Exception ignored){}return null;}
    private String currentAdvice(Feedback f){JSONObject c=cached(f,Ui.model(this));if(c!=null)return c.optString("text");if(f.pending&&Ui.model(this).equals(f.pendingModel))return "방금 수의 판단과 다음 계획을 생각하고 있어요…";if(!ChatGptAccounts.connected(this))return "AI 코치를 연결하면 방금 수의 이유와 다음 계획을 알려드려요. 연결하기 →";return f.ai.isEmpty()||!Ui.model(this).equals(f.aiModel)?"이 모델의 조언을 받아 보세요. 아래 다시 설명을 누르면 됩니다.":f.ai;}
    private void renderFeedback(){planUse.setText(ChatGptAccounts.connected(this)?"Using ChatGPT plan · Manage usage":"ChatGPT 연결 · Manage usage");if(coach==null)return;modelChip.setText(Ui.modelLabel(this)+" ⌄");board.recommendation=board.playedArrow=null;board.judgedSquare=-1;board.judgment=MoveJudgment.Kind.UNKNOWN;moveLabel.setText("");
        if(focus>=0&&focus<feedback.size()){Feedback f=feedback.get(focus);String advice=currentAdvice(f);if(advice.startsWith("CODEX /")||advice.startsWith("CHATGPT /")){int line=advice.indexOf('\n');if(line>=0)advice=advice.substring(line+1);}coach.setText(advice);try{if(f.details!=null){var a=AnalysisJson.analysis(f.details.getJSONObject("analysis"));var actual=f.details.isNull("playedScore")?null:AnalysisJson.line(f.details.getJSONObject("playedScore"));Chess before=new Chess(focus==0?Chess.START:fens.get(focus-1));var result=MoveJudgment.assess(before,moves.get(focus),a,actual);board.judgment=result.kind();board.judgedSquare=Chess.Move.parse(moves.get(focus)).to();moveLabel.setText(result.kind().symbol+" "+result.kind().label);moveLabel.setTextColor(INK);if(preview&&a.top()!=null&&!a.top().pv().isEmpty()){board.recommendation=a.top().pv().get(0);board.playedArrow=moves.get(focus);}}}catch(Exception ignored){}}
        else coach.setText(!ChatGptAccounts.connected(this)?"기물을 선택해 첫 수를 두세요. AI 코치 연결하기 →":"첫 수를 두면 판단의 근거와 다음 계획을 알려드려요.");board.invalidate();
    }
    private void refresh(){if(board==null)return;board.board=preview&&focus>=0?new Chess(focus==0?Chess.START:fens.get(focus-1)):game;int lastPlayed=preview&&focus>=0?focus-1:moves.size()-1;board.setLastMove(lastPlayed>=0?Chess.Move.parse(moves.get(lastPlayed)):null);if(preview){board.selected=-1;board.targets.clear();}String terminal=game.terminal(repetitions.getOrDefault(game.key(),1));status.setText(preview?"추천 이동 미리보기 · 착수 전 국면":terminal!=null?terminal:busy?"수 분석 중…":game.white?"내 차례 · "+Difficulty.from(prefs.getString("difficulty","ELO_1600")).label:"상대 차례");suggestion.setText(preview?"대국으로 돌아가기":"추천수 보기");suggestion.setEnabled(focus>=0&&feedback.get(focus).details!=null);undoButton.setEnabled(!busy&&!moves.isEmpty());renderFeedback();moveStrip.removeAllViews();for(int i=Math.max(0,moves.size()-12);i<moves.size();i++){final int ply=i;Chess before=new Chess(i==0?Chess.START:fens.get(i-1));Button b=button((i/2+1)+(i%2==0?". ":"… ")+before.san(Chess.Move.parse(moves.get(i))),()->{focus=ply;preview=true;refresh();});b.setTextSize(12);b.setMinHeight(dp(32));if(i==focus)b.setTextColor(0xFF428965);moveStrip.addView(b,new LinearLayout.LayoutParams(-2,dp(36)));}}
    private void undo(){if(busy||moves.isEmpty())return;generation++;int keep=Math.max(0,moves.size()-(game.white?2:1));while(moves.size()>keep){moves.remove(moves.size()-1);fens.remove(fens.size()-1);feedback.remove(feedback.size()-1);}game=new Chess(keep==0?Chess.START:fens.get(keep-1));focus=keep==0?-1:Math.max(0,keep-2);preview=false;rebuildRepetitions();restoreEvaluation();board.selected=-1;board.targets.clear();save();refresh();}
    private void rebuildRepetitions(){repetitions.clear();repetitions.put(new Chess().key(),1);for(String fen:fens)repetitions.merge(new Chess(fen).key(),1,Integer::sum);}
    private void save(){
        JSONArray entries=new JSONArray();
        try {for(Feedback f:feedback)entries.put(new JSONObject().put("local",f.local).put("ai",f.pending?"설명 대기 · 다시 연결해 재시도하세요":f.ai).put("payload",f.payload==null?JSONObject.NULL:f.payload));}
        catch(JSONException ignored){}
        if(!moves.isEmpty()){
            Pgn.Game pgn=Pgn.parse(String.join(" ",moves));String terminal=game.terminal(repetitions.getOrDefault(game.key(),1));String result=terminal==null?"*":terminal.startsWith("백 승리")?"1-0":terminal.startsWith("흑 승리")?"0-1":"1/2-1/2";pgn=new Pgn.Game(pgn.initial(),pgn.plies(),pgn.tags(),result);
            if(recordId==0)recordId=Records.get(this).create("Stockfish · "+Difficulty.from(prefs.getString("difficulty","ELO_1600")).label,"played",pgn);else Records.get(this).updateGame(recordId,pgn);
        }else if(recordId!=0)Records.get(this).updateGame(recordId,new Pgn.Game(Chess.START,Collections.emptyList(),Collections.emptyMap(),"*"));
        prefs.edit().putString("moves",String.join(" ",moves)).putString("feedback",entries.toString()).putLong("activeRecord",recordId).apply();
    }
    private void persistFeedback(Feedback entry,int ply){try{JSONObject patch=new JSONObject().put("local",entry.local);if(entry.payload!=null)patch.put("payload",entry.payload);if(entry.details!=null)patch.put("details",entry.details);Records.get(this).patch(recordId,ply,patch);}catch(Exception ignored){}}
    private void restore(){
        try{
            recordId=prefs.getLong("activeRecord",0);
            String saved=prefs.getString("moves","");
            if(!saved.trim().isEmpty())for(String u:saved.split(" ")){game.play(Chess.Move.parse(u));moves.add(u);fens.add(game.fen());feedback.add(new Feedback((moves.size()%2==1?"백 ":"흑 ")+u+" · 저장된 대국"));}
            JSONArray entries=new JSONArray(prefs.getString("feedback","[]"));
            for(int i=0;i<Math.min(entries.length(),feedback.size());i++){JSONObject entry=entries.getJSONObject(i);Feedback f=feedback.get(i);f.local=entry.getString("local");f.ai=entry.optString("ai");f.payload=entry.optJSONObject("payload");}
            Records.Saved record=recordId==0?null:Records.get(this).find(recordId);
            if(record!=null)for(int i=0;i<feedback.size();i++){JSONObject entry=record.analyses().optJSONObject(Integer.toString(i));if(entry!=null){Feedback f=feedback.get(i);f.local=entry.optString("local",f.local);f.ai=entry.optString("aiText",f.ai);f.payload=entry.optJSONObject("payload");f.details=entry.optJSONObject("details");}}
        }catch(Exception e){game=new Chess();moves.clear();fens.clear();feedback.clear();save();}
        rebuildRepetitions();restoreEvaluation();focus=feedback.isEmpty()?-1:Math.max(0,feedback.size()-(game.white?2:1));refresh();
    }
    private void restoreEvaluation(){
        trend.clear();String label="백 기준 평가 · 분석 대기";
        for(int i=Math.max(0,feedback.size()-6);i<feedback.size();i++){
            JSONObject details=feedback.get(i).details;if(details==null)continue;
            try{JSONObject after=details.optJSONObject("afterAnalysis");if(after==null)continue;
                Stockfish.Line top=AnalysisJson.analysis(after).top();if(top==null)continue;
                trend.add(top.cp());if(i==feedback.size()-1)label="백 기준 "+top.score()+" · 탐색 깊이 "+top.depth()+" · 저장된 평가";
            }catch(JSONException ignored){}
        }
        evaluation.setText(label);
    }
    private void closeEngines(){if(engine!=null)engine.close();if(opponent!=null)opponent.close();engine=null;opponent=null;}
    @Override protected void onStart(){super.onStart();if(parked){parked=false;connectEngine();}if(modelChip!=null){renderFeedback();if(focus>=0)requestExplanation(feedback.get(focus),generation);}}
    @Override protected void onStop(){parked=true;super.onStop();if(!destroyed)engineJobs.submit(()->{if(parked)closeEngines();});}
    @Override protected void onDestroy(){destroyed=true;generation++;engineJobs.shutdownNow();coachJobs.shutdownNow();EngineWork.close(this::closeEngines);super.onDestroy();}
}
