package com.chesscoach.app;
import android.app.Activity;
import android.os.Bundle;
import android.content.Intent;
import android.widget.*;
import java.util.*;
public final class RecordsActivity extends Activity {
    private LinearLayout root,list;private int filter=0;private final Button[] filters=new Button[3];
    @Override public void onCreate(Bundle state){super.onCreate(state);root=Ui.screen(this,true);LinearLayout header=new LinearLayout(this);header.setGravity(android.view.Gravity.CENTER_VERTICAL);header.addView(Ui.button(this,"‹",this::finish),new LinearLayout.LayoutParams(Ui.dp(this,44),Ui.dp(this,44)));TextView title=Ui.text(this,"대국 기록",22,true);title.setPadding(Ui.dp(this,10),0,0,0);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));header.addView(Ui.primary(this,"+ 기록 추가",()->startActivity(new Intent(this,ImportActivity.class))));root.addView(header);Ui.gap(root,16);root.addView(Ui.text(this,"지난 수에서, 다음 실력을 발견하세요.",15,false));Ui.gap(root,16);LinearLayout tabs=new LinearLayout(this);for(int i=0;i<3;i++){final int selected=i;Button b=Ui.button(this,new String[]{"전체","직접 대국","가져온 기보"}[i],()->{filter=selected;render();});filters[i]=b;tabs.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));}root.addView(tabs);Ui.gap(root,16);list=Ui.column(this);root.addView(list);}
    @Override public void onResume(){super.onResume();render();}
    private void render(){for(int i=0;i<filters.length;i++){Button b=filters[i];Ui.selected(this,b,i==filter);}list.removeAllViews();List<Records.Saved> games=Records.get(this).list();int shown=0;for(var game:games){if(filter==1&&!game.origin().equals("played")||filter==2&&!game.origin().equals("imported"))continue;shown++;LinearLayout card=Ui.card(this);TextView tag=Ui.text(this,game.origin().equals("played")?"PLAY  ·  직접 대국":"IMPORT  ·  가져온 기보",11,true);tag.setTextColor(getColor(R.color.muted));card.addView(tag);Ui.gap(card,8);card.addView(Ui.text(this,game.title(),19,true));Ui.gap(card,6);try{String savedResult=GameOutcome.savedResult(game.pgn());var outcome=GameOutcome.from(savedResult,game.origin().equals("played"),null);if(outcome!=null){TextView result=Ui.text(this,outcome.title()+"  ·  "+savedResult,13,true);result.setTextColor(getColor(outcome.kind()==GameOutcome.Kind.LOSS?R.color.danger:outcome.kind()==GameOutcome.Kind.WIN?R.color.success:R.color.accent));card.addView(result);}}catch(Exception ignored){}String date=new java.text.SimpleDateFormat("MM.dd  HH:mm",Locale.getDefault()).format(new Date(game.created()));card.addView(Ui.text(this,date+"  ·  "+game.plies()+" 반수",13,false));int ai=0,analyzed=0;Iterator<String> keys=game.analyses().keys();while(keys.hasNext()){var e=game.analyses().optJSONObject(keys.next());if(e!=null){if(e.has("aiResponse"))ai++;if(e.has("details"))analyzed++;}}Ui.gap(card,14);card.addView(Ui.text(this,"분석 "+analyzed+" / "+game.plies()+"    조언 "+ai+"    하이라이트 "+game.highlights().length()+"   →",13,true));card.setOnClickListener(v->startActivity(new Intent(this,ReviewActivity.class).putExtra("recordId",game.id())));card.setContentDescription(game.title()+" 복기 열기");list.addView(card);Ui.gap(list,12);}if(shown==0){LinearLayout empty=Ui.card(this);empty.addView(Ui.text(this,"첫 기록을 남겨 보세요.",23,true));Ui.gap(empty,12);empty.addView(Ui.text(this,"대국을 시작하거나 PGN 기보를 추가하면\n수와 조언을 여기에서 다시 볼 수 있어요.",15,false));Ui.gap(empty,20);empty.addView(Ui.primary(this,"Stockfish와 대국",()->startActivity(new Intent(this,GameSetupActivity.class))));list.addView(empty);}}
}
