package com.chesscoach.app;
import android.os.Bundle;
import android.content.Intent;
import android.text.*;
import android.widget.*;

/** One app settings screen; teaching changes affect future requests, not saved explanations. */
public final class SettingsActivity extends ThemedActivity {
    @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout root=Ui.screen(this,true);LinearLayout header=new LinearLayout(this);header.setGravity(android.view.Gravity.CENTER_VERTICAL);header.addView(Ui.link(this,"‹",this::finish),new LinearLayout.LayoutParams(Ui.dp(this,44),Ui.dp(this,44)));header.addView(Ui.text(this,"설정",24,true));root.addView(header);Ui.gap(root,20);
        LinearLayout appearance=Ui.card(this);appearance.addView(Ui.text(this,"화면",19,true));Appearance.controls(this,appearance,this::recreate);root.addView(appearance);Ui.gap(root,20);
        LinearLayout coaching=Ui.card(this);coaching.addView(Ui.text(this,"AI 설명 방식",19,true));Ui.gap(coaching,8);var prefs=getSharedPreferences("coach",0);addSwitch(coaching,"설명 요약","핵심 전략과 배울 원칙을 짧게 설명해요.","conciseAdvice");addSwitch(coaching,"초보자에게 설명","전문용어 대신 쉬운 말과 기물 이름으로 설명해요.","beginnerAdvice");Ui.gap(coaching,16);coaching.addView(Ui.text(this,"추가 프롬프트",15,true));Ui.gap(coaching,8);EditText prompt=new EditText(this);prompt.setTextColor(getColor(R.color.ink));prompt.setHintTextColor(getColor(R.color.muted));prompt.setHint("예: 다음 수 전에 스스로 확인할 질문을 제시해 주세요.");prompt.setTextSize(14);prompt.setMinLines(3);prompt.setMaxLines(8);prompt.setGravity(android.view.Gravity.TOP);prompt.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);prompt.setFilters(new InputFilter[]{new InputFilter.LengthFilter(CoachPreferences.LIMIT)});prompt.setText(prefs.getString("extraPrompt",""));coaching.addView(prompt,new LinearLayout.LayoutParams(-1,-2));TextView note=Ui.text(this,"자동 저장 · 최대 2,000자\n새 AI 요청부터 적용됩니다. 기존 해설은 그대로 보관해요.",12,false);note.setTextColor(getColor(R.color.muted));coaching.addView(note);prompt.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){prefs.edit().putString("extraPrompt",s.toString()).apply();}public void afterTextChanged(Editable e){}});root.addView(coaching);Ui.gap(root,20);root.addView(Ui.button(this,"AI 코치 연결 · 기본 모델",()->startActivity(new Intent(this,ConnectionActivity.class))));
    }
    private void addSwitch(LinearLayout root,String label,String description,String key){var prefs=getSharedPreferences("coach",0);Switch toggle=new Switch(this);toggle.setText(label);toggle.setTextSize(15);toggle.setTextColor(getColor(R.color.ink));toggle.setMinHeight(Ui.dp(this,48));toggle.setChecked(prefs.getBoolean(key,false));toggle.setOnCheckedChangeListener((v,on)->prefs.edit().putBoolean(key,on).apply());root.addView(toggle);TextView note=Ui.text(this,description,12,false);note.setTextColor(getColor(R.color.muted));root.addView(note);Ui.gap(root,8);}
}
